config/routes.rb
# Configure the GraphQL API
# config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  
  root "home#index"
  get 'category/:handle', to: 'categories#show', as: 'category'
  get 'posts/:handle', to: 'posts#show', as: 'post'

  post "/graphql", to: "graphql#execute"
  get "rails/csrf-token", to: "rails#csrf_token"

  resources :posts, param: :handle, only: [:show]
  resources :categories, param: :handle, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  validates :priority, presence: true
  validates :color, presence: true
  before_save :generate_handle

  has_and_belongs_to_many :posts

  def posts_by_year
    posts.where(published: true).each_with_object({}) do |post, posts_by_year|
      post_year = post.created_at.year
      posts_by_year[post_year] ||= []
      posts_by_year[post_year].append(post)
    end.sort_by { |key, _| key }.reverse.to_h
  end

  private

  def generate_handle
    self.handle = name.downcase.tr(" ", "-")
  end
end

app/models/configuration.rb
class Configuration < ApplicationRecord
  validate :there_can_only_be_one
  validates :name, presence: true, uniqueness: true
  validates :bio, presence: true
  validates :profile_picture, presence: true

  def there_can_only_be_one
    errors[:base] << "There can only be one" if Configuration.count.positive?
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :description, presence: true
  validates :pinned, inclusion: { in: [true, false] }

  has_and_belongs_to_many :categories

  before_save :generate_handle

  def self.posts_by_year
    where(published: true).order(created_at: :desc).each_with_object({}) do |post, posts_by_year|
      post_year = post.created_at.year
      posts_by_year[post_year] ||= []
      posts_by_year[post_year].append(post)
    end.sort_by { |key, _| key }.reverse.to_h
  end

  # Use Redcarpet gem to render Markdown content
  def rendered_content
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
    markdown.render(content).html_safe
  end

  private

  def generate_handle
    self.handle = title.downcase.tr(" ", "-")
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Trestle::Auth::ModelMethods
  include Trestle::Auth::ModelMethods::Rememberable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_header_details

  def set_header_details
    @categories = Category.all
    @blog_configuration = ::Configuration.first
    @home_icon_color = params[:category_id].present? ? "is-link is-light" : "is-link"
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find_by(handle: params[:handle])
    @posts_by_year = @category.posts_by_year
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts_by_year = Post.posts_by_year
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find_by(handle: params[:handle])
  end
end

app/controllers/rails_controller.rb
class RailsController < ApplicationController
  def csrf_token
    response.headers["X-CSRF-Token"] = form_authenticity_token

    response
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/show.html.erb
<% if @posts_by_year.any? %>
  <%= render 'shared/post_layout' %>
<% else %>
  <%= render 'shared/no_results' %>
<% end %>

app/views/home/index.html.erb
 <%= render 'shared/post_layout' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Logan Gunn - blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.3/css/bulma.min.css"
    >
    <%= javascript_importmap_tags %>

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    >

    <style>
      .card-hover {
        cursor: pointer;
        transition: transform 0.2s ease-in-out;
      }

      .card-hover:hover {
        transform: scale(1.05);
        box-shadow: 0px 5px 10px rgba(0, 0, 0, 0.1);
      }

      .tag-clickable {
        cursor: pointer;
        transition: opacity 0.3s ease;
      }

      .tag-clickable:hover {
        opacity: 0.7;
      }
    </style>

    <link rel="shortcut icon" type="image/x-icon" href="/logo192.png">
  </head>

  <body>
    <section class="hero is-light">
      <%= render "shared/header" %>
    </section>
    <%= yield %>

  </body>
</html>

app/views/posts/show.html.erb
<!-- Blog post section -->
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="card">
          <div class="card-content">
            <div class="content">
              <h3 class="title"><%= @post.title %></h3>
              <p class="subtitle"><%= @post.created_at.strftime("%B %d, %Y") %></p>
              <%= @post.rendered_content %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="has-text-centered">
      <a href="/" class="button is-link is-light">Back to Home</a>
    </div>
  </div>
</section>

app/views/shared/_header.html.erb
<div class="hero-body">
  <div class="container has-text-centered">
    <div class="columns is-centered">
      <div class="column is-one-third mx-auto">
        <!-- Profile image -->
        <%= link_to root_path do %>
          <figure class="image is-128x128" style="margin: 0 auto">
            <img
              class="is-rounded"
              src=<%= @blog_configuration.profile_picture %>
              alt="Profile Image"
            >
          </figure>
        <% end %>
      </div>
    </div>
    <h1 class="title"><%= @blog_configuration.name %></h1>
    <h2 class="subtitle"><%= @blog_configuration.bio %></h2>
    <div class="content">
      <a href="https://logangunn.com" class="button is-small is-rounded is-link">🧑🏻‍💻 Visit my website</a>
    </div>

    <div class="tags is-centered">
      <%= link_to root_path do %>
        <span class="tag <%= @home_icon_color %>">
          <i class="fas fa-home"></i>
        </span>
      <% end %>
      <% @categories.each do |category| %>
        <%= link_to category_path(handle: category.handle), class: 'my-link' do %>
          <% if @category&.id == category.id %>
            <span class="tag tag-clickable is-link"><%= category.name %></span>
          <% else %>
            <span class="tag tag-clickable is-link is-light"><%= category.name %></span>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

app/views/shared/_no_results.html.erb
<section class="section">
    <div class="container has-text-centered">
        <div class="notification">
            <p class="subtitle ">No results found for this category.</p>
        </div>
    </div>
</section>

app/views/shared/_post_layout.html.erb
<!-- Blog posts section -->
<section class="section">
  <% @posts_by_year.keys.each do |year| %>
    <div class="title is-4"><%= year %></div>
    <div class="columns is-multiline is-vcentered">
      <% @posts_by_year[year].each do |post| %>
        <div class="column is-one-third">
          <%= link_to post_path(handle: post.handle), class: 'my-link' do %>
            <div class="card card-hover">
              <div class="card-content">
                <div class="content">
                  <p class="title is-4"><%= post.title %></p>
                  <p class="subtitle is-6"><%= post.created_at.strftime("%B %d, %Y") %></p>
                  <p><%= truncate(post.description, length: 120) %></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</section>